const ACTION_TYPES = {
    START_RACE: "START_RACE",
    ENTER_CORRIDOR: "ENTER_CORRIDOR",
    RACE_STARTED: "RACE_STARTED",
    RACE_ENDED: "RACE_ENDED",

    FINISH: "FINISH",
    END_RACE: "END_RACE",
    ATHLETE_ENTERED_CORRIDOR: "ATHLETE_ENTERED_CORRIDOR",
    ATHLETE_FINISHED: "ATHLETE_FINISHED",
    FETCH_ATHLETES: "FETCH_ATHLETES",
    RECEIVE_ATHLETES: "RECEIVE_ATHLETES",

    RECEIVE_FINISHING_ATHLETES: "RECEIVE_FINISHING_ATHLETES"
};

module.exports = ACTION_TYPES;